# Generated by Django 4.2.5 on 2023-10-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
