# Generated by Django 4.2.5 on 2023-10-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_date_ajout'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
